### ISSUE TITLE
No clear project structure

### ISSUE THREAD

**Issue by DaanAcohen** [EdCharbeneau/csharp-functional-workshop#1]
I would like to see a nice project structure.  All C# parts that belong together can be put in a shared project. Each shared project can be compiled as part of a .NET Core project and a .NET Framework project. This is better than using the .NET Standard because such a solution requires the .NET core to be installed anyway. Can you give me rights to create my own branch? I have my branch locally and I would like to commit and later when finished do a pull request to merge to master.

**Comment by EdCharbeneau** [comment]
Thanks for sharing interest in my project. You should be able to fork the project. Once forked you can create a branch, do work, and submit a pull request back to my repository.

**Comment by EdCharbeneau** [comment]
Feedback considered  and reworking for .NET 9
